services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: face-rec-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/training:/app/training
      - ./backend/face_data:/app/face_data
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: face-rec-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend
    restart: always